import {loadDashboard,refreshRemote,getGasUrl,setGasUrl,nutritionSummary} from './data-source.js';
import {renderNutrition,bindNutrition} from './nutrition-ui.js';

const main=document.getElementById('appMain');
const title=document.getElementById('pageTitle');
const dateLabel=document.getElementById('dateLabel');
const syncBtn=document.getElementById('syncBtn');
let data=await loadDashboard();
let route='today';
let nutritionChartKey='kcal';
const now=new Date();
const todayText=new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'long'}).format(now);
const detailDate=new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric'}).format(now);
dateLabel.textContent=todayText;

const clamp=(v,a=0,b=100)=>Math.min(b,Math.max(a,v));
const fmtMin=m=>`${Math.floor(m/60)}시간 ${m%60}분`;

function smoothPath(points){if(points.length<2)return'';let d=`M ${points[0].x} ${points[0].y}`;for(let i=0;i<points.length-1;i++){const p0=points[i-1]||points[i],p1=points[i],p2=points[i+1],p3=points[i+2]||p2;d+=` C ${p1.x+(p2.x-p0.x)/6} ${p1.y+(p2.y-p0.y)/6}, ${p2.x-(p3.x-p1.x)/6} ${p2.y-(p3.y-p1.y)/6}, ${p2.x} ${p2.y}`;}return d;}
function lineChart(values,{color='#59d3dc',unit='',baseline=null,labels=['월','화','수','목','금','토','오늘'],height=208,rightAxis=false}={}){const w=356,h=height,l=rightAxis?8:34,r=rightAxis?34:10,t=16,b=28;const ext=[...values];if(baseline!=null)ext.push(baseline);const lo=Math.min(...ext),hi=Math.max(...ext),pad=Math.max(2,(hi-lo)*.18),min=lo-pad,max=hi+pad,range=max-min||1,X=i=>l+i*(w-l-r)/(values.length-1),Y=v=>t+(max-v)*(h-t-b)/range,pts=values.map((v,i)=>({x:X(i),y:Y(v),v})),path=smoothPath(pts),area=`${path} L ${pts.at(-1).x} ${h-b} L ${pts[0].x} ${h-b} Z`,gid=`a${Math.random().toString(36).slice(2)}`,ticks=[max,max-range/3,max-range*2/3,min];return `<svg class="pro-chart" viewBox="0 0 ${w} ${h}"><defs><linearGradient id="${gid}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${color}" stop-opacity=".24"/><stop offset="1" stop-color="${color}" stop-opacity="0"/></linearGradient></defs>${ticks.map(v=>`<line x1="${l}" x2="${w-r}" y1="${Y(v)}" y2="${Y(v)}" class="chart-grid"/><text x="${rightAxis?w-2:2}" y="${Y(v)+3}" text-anchor="${rightAxis?'end':'start'}" class="chart-axis">${Math.round(v*10)/10}${unit}</text>`).join('')}${baseline!=null?`<line x1="${l}" x2="${w-r}" y1="${Y(baseline)}" y2="${Y(baseline)}" class="chart-baseline"/>`:''}<path d="${area}" fill="url(#${gid})"/><path d="${path}" fill="none" stroke="${color}" stroke-width="3.1" stroke-linecap="round"/><circle cx="${pts.at(-1).x}" cy="${pts.at(-1).y}" r="5" fill="#0b0d10" stroke="${color}" stroke-width="3"/>${labels.slice(0,values.length).map((x,i)=>`<text x="${X(i)}" y="${h-7}" text-anchor="middle" class="chart-x">${x}</text>`).join('')}</svg>`;}
function barChart(values,{color='#5dc5c0',max=100,labels=['월','화','수','목','금','토','일','오늘']}={}){return `<div class="bar-chart-pro"><div class="bar-grid"><i></i><i></i><i></i><i></i></div><div class="bar-series">${values.map((v,i)=>`<div class="bar-item"><b style="height:${Math.max(2,v/max*100)}%;background:${i===values.length-1?'#555':color}"></b><span>${labels[i]||''}</span></div>`).join('')}</div><div class="bar-axis"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div></div>`;}
function ring(value,color,label){const r=40,c=2*Math.PI*r,d=c*clamp(value)/100;return `<div class="ring-wrap"><svg viewBox="0 0 100 100"><circle class="ring-track" cx="50" cy="50" r="40"/><circle class="ring-value" cx="50" cy="50" r="40" style="stroke:${color};stroke-dasharray:${d} ${c-d}"/></svg><div class="ring-center"><strong>${Math.round(value)}<small>%</small></strong><span>${label}</span></div></div>`;}
function rangeBar(value,{type='recovery',targetMin=null,targetMax=null}={}){return `<div class="range-viz ${type}"><div class="range-track">${targetMin!=null?`<i class="target" style="left:${targetMin}%;width:${targetMax-targetMin}%"></i>`:''}<b class="cursor" style="left:${clamp(value)}%"></b></div><div class="range-labels"><span>낮음</span><span>보통</span><span>양호</span><span>높음</span></div></div>`;}
function metricCard(key,label,score,status,color,visual){return `<button class="metric-card premium" data-detail="${key}" style="--accent:${color}"><div class="metric-head"><span>${label}</span><span>›</span></div><div class="metric-art">${visual}</div><div class="metric-foot"><strong>${Math.round(score)}<small>%</small></strong><span>${status}</span></div></button>`;}
function sleepTimeline(){const s=data.today.sleep,blocks=[['깊음',17,'#3458ca'],['코어',26,'#5176ff'],['REM',11,'#a063ff'],['코어',21,'#5176ff'],['깊음',9,'#3458ca'],['코어',8,'#5176ff'],['REM',6,'#a063ff'],['깨어남',2,'#ff786b']];return `<div class="sleep-timeline"><div class="sleep-hours"><span>23:00</span><span>02:00</span><span>05:00</span><span>08:00</span></div><div class="sleep-lanes">${blocks.map(x=>`<i style="width:${x[1]}%;background:${x[2]}"></i>`).join('')}</div><div class="sleep-legend"><span><i style="background:#a063ff"></i>REM ${s.rem}분</span><span><i style="background:#5176ff"></i>코어</span><span><i style="background:#3458ca"></i>깊음 ${s.deep}분</span></div></div>`;}
function todayNutritionCard(){const s=nutritionSummary(data),g=s.goals;return `<section class="nutrition-card"><div class="card-head"><div><span class="eyebrow">NUTRITION</span><h2>오늘의 식단</h2></div><button class="soft-btn" data-route-go="journal">기록</button></div><div class="calorie-row"><div><strong>${Math.round(s.kcal).toLocaleString()}</strong><span>/ ${g.kcal.toLocaleString()} kcal</span></div><div class="calorie-progress"><i style="width:${clamp(s.kcal/g.kcal*100)}%"></i></div></div><div class="body-strip compact"><div><span>단백질</span><strong>${Math.round(s.protein)}<small> / ${g.protein}g</small></strong></div><div><span>탄수화물</span><strong>${Math.round(s.carbs)}<small> / ${g.carbs}g</small></strong></div><div><span>지방</span><strong>${Math.round(s.fat)}<small> / ${g.fat}g</small></strong></div></div></section>`;}
function todayView(){const t=data.today;return `<div class="fade-in"><section class="hero-command"><div><span class="eyebrow">DAILY READINESS</span><h2>오늘 컨디션은 <b>좋은 편</b>입니다</h2><p>회복과 수면을 기준으로 현재 상태를 빠르게 확인합니다.</p></div><div class="hero-rings">${ring(t.recovery.score,'#5bd7df','회복')}${ring(t.sleep.quality,'#8a6dff','수면')}</div></section><div class="section-label"><h2>오늘의 상태</h2><span>${new Date(data.updatedAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</span></div><section class="metric-grid">${metricCard('recovery','회복',t.recovery.score,t.recovery.status,'#5bd7df',lineChart(t.recovery.trend,{color:'#5bd7df',height:102,labels:['','','','','','','']}))}${metricCard('stress','스트레스',t.stress.score,t.stress.status,'#7f73ff',rangeBar(t.stress.score,{type:'stress'}))}${metricCard('energy','신체 에너지',t.energy.score,t.energy.status,'#51d485',rangeBar(t.energy.score,{type:'energy'}))}${metricCard('training','운동 강도',t.training.score,t.training.status,'#d764aa',rangeBar(t.training.score,{type:'training',targetMin:t.training.targetMin,targetMax:t.training.targetMax}))}</section><button class="sleep-premium" data-detail="sleep"><div class="card-head"><div><span class="eyebrow">SLEEP</span><h2>${fmtMin(t.sleep.minutes)}</h2></div><div class="sleep-score"><strong>${t.sleep.quality}</strong><span>품질</span></div></div>${sleepTimeline()}</button>${todayNutritionCard()}<section class="body-strip"><div><span>HRV</span><strong>${t.vitals.hrv}<small> ms</small></strong></div><div><span>안정 시 심박</span><strong>${t.vitals.rhr}<small> bpm</small></strong></div><div><span>SpO₂</span><strong>${t.vitals.spo2}<small>%</small></strong></div></section></div>`;}
function detailTop(label){return `<div class="pro-topbar"><button data-back aria-label="뒤로가기">‹</button><div><strong>${label}</strong><span>${detailDate}⌄</span></div><button aria-label="공유">⇧</button></div>`;}
function stressView(){const s=data.today.stress;return `<div class="pro-page pro-stress fade-in">${detailTop('스트레스')}<section class="pro-metric-hero"><div class="hero-score-block"><strong>${s.score}<small>%</small></strong><span>${s.status}</span></div>${rangeBar(s.score,{type:'stress'})}</section><section class="pro-stats-row"><div><span>평균 스트레스</span><strong>${s.avg}%</strong><small>14일 평균 ${s.avgBaseline}%</small></div><div><span>안정 시 심박</span><strong>${s.rhr}<small>bpm</small></strong><small>개인 기준 비교</small></div></section><section class="pro-insight"><span>✦</span><p>현재 스트레스는 HRV·심박·수면·최근 훈련부하를 함께 반영한 내부 추정치입니다.</p><b>⌄</b></section><section class="pro-chart-section"><div class="chart-heading"><h2>스트레스 추이</h2><span>7일</span></div><div class="trend-summary"><div><span>피크</span><strong>${Math.max(...s.trend)}%</strong></div><div><span>최소</span><strong>${Math.min(...s.trend)}%</strong></div><div><span>평균</span><strong>${Math.round(s.trend.reduce((a,b)=>a+b,0)/s.trend.length)}%</strong></div></div>${barChart([...s.trend,s.score],{color:'#5fc5bf',labels:['화','수','목','금','토','일','월','오늘']})}<div class="period-control"><button class="active">7일</button><button>14일</button><button>30일</button></div></section></div>`;}
function energyView(){const e=data.today.energy;return `<div class="pro-page pro-energy fade-in">${detailTop('신체 에너지')}<section class="pro-metric-hero energy-hero"><div class="hero-score-block"><strong>${e.score}<small>%</small></strong><span>${e.status}</span></div><div class="range-copy"><span>오늘 범위</span><strong>${e.rangeMin}%~${e.rangeMax}%</strong></div>${rangeBar(e.score,{type:'energy'})}</section><section class="pro-stats-row"><div><span>야간 충전</span><strong>${e.overnightCharge}%</strong><small>14일 평균 기반</small></div><div><span>주간 소모</span><strong>${e.dayDrain}%</strong><small>활동·운동 기반</small></div></section><section class="pro-insight"><span>✦</span><p>몸의 에너지가 낮아질수록 회복과 수면을 우선하는 편이 좋습니다.</p><b>⌄</b></section><section class="pro-chart-section"><div class="chart-heading"><h2>일일 에너지 곡선</h2><span>ⓘ</span></div>${lineChart(e.trend,{color:'#55d276',labels:['23:18','','','','11:36','','','23:54'],height:238,rightAxis:true})}</section></div>`;}
function recoveryView(){const r=data.today.recovery;return `<div class="pro-page pro-recovery fade-in">${detailTop('회복')}<section class="pro-metric-hero"><div class="hero-score-block"><strong>${r.score}<small>%</small></strong><span>${r.status}</span></div>${rangeBar(r.score,{type:'recovery'})}</section><section class="pro-stats-row"><div><span>오늘 평균 HRV</span><strong>${r.hrv}<small>ms</small></strong><small>14일 ${r.hrvBaseline}ms</small></div><div><span>안정 시 심박</span><strong>${r.rhr}<small>bpm</small></strong><small>14일 ${r.rhrBaseline}bpm</small></div></section><section class="pro-insight"><span>✦</span><p>HRV가 개인 기준선보다 높고 안정 시 심박은 낮아 회복 상태가 양호합니다.</p><b>⌄</b></section><section class="pro-chart-section"><div class="chart-heading"><h2>HRV 추이</h2><span>7일</span></div>${lineChart(r.trend,{color:'#59d3dc',baseline:r.hrvBaseline,unit:' ms'})}</section></div>`;}
function trainingIntensityView(){const t=data.today.training;return `<div class="pro-page pro-training fade-in">${detailTop('운동 강도')}<section class="pro-metric-hero"><div class="hero-score-block"><strong>${t.score}<small>%</small></strong><span>${t.status}</span></div><div class="range-copy"><span>권장 범위</span><strong>${t.targetMin}%~${t.targetMax}%</strong></div>${rangeBar(t.score,{type:'training',targetMin:t.targetMin,targetMax:t.targetMax})}</section><section class="pro-stats-row"><div><span>회복 점수</span><strong>${t.recovery}%</strong><small>오늘 상태 반영</small></div><div><span>활동 에너지</span><strong>${t.calories}<small>kcal</small></strong><small>오늘 누적</small></div></section><section class="pro-insight"><span>✦</span><p>현재 운동 강도는 권장 범위보다 낮습니다. 컨디션이 유지되면 강도를 조금 높일 수 있습니다.</p><b>⌄</b></section></div>`;}
function sleepView(){const s=data.today.sleep;return `<div class="pro-page pro-sleep fade-in">${detailTop('수면')}<section class="pro-metric-hero"><div class="hero-score-block"><strong>${s.quality}<small>%</small></strong><span>수면 품질</span></div><div class="range-copy"><span>총 수면</span><strong>${fmtMin(s.minutes)}</strong></div>${rangeBar(s.quality,{type:'sleep'})}</section><section class="pro-chart-section"><div class="chart-heading"><h2>수면 단계</h2><span>지난밤</span></div>${sleepTimeline()}</section><section class="sleep-factor-list">${[['깊은 수면',s.deep+'분','회복성 수면'],['REM',s.rem+'분','인지 회복'],['효율',s.efficiency+'%','침대 대비 수면'],['규칙성',s.consistency+'%','취침·기상 일관성']].map(x=>`<div><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('')}</section></div>`;}
function healthView(){const v=data.today.vitals;return `<div class="fade-in"><div class="page-intro"><span class="eyebrow">HEALTH</span><h2>건강 지표</h2><p>회복·심폐·체성분을 한 화면에서 확인합니다.</p></div><section class="health-hero"><div><span>VO₂ Max</span><strong>${v.vo2max}</strong><small>최근 측정값</small></div>${ring(72,'#5d8cff','심폐')}</section><section class="premium-list">${[['HRV',`${v.hrv} ms`,'회복 상태','#5ad4d8'],['안정 시 심박',`${v.rhr} bpm`,'심혈관','#5d8cff'],['호흡수',`${v.resp} BrPM`,'호흡','#8d71ff'],['혈중 산소',`${v.spo2}%`,'산소포화도','#50d286'],['체중',`${v.weight} kg`,'체성분','#ffb348'],['BMI',v.bmi,'체성분','#ff8d49'],['체지방률',`${v.bodyFat}%`,'체성분','#f06b7e'],['제지방량',`${v.leanMass} kg`,'체성분','#5bb4ff']].map(x=>`<div class="premium-row" style="--row:${x[3]}"><i></i><div><span>${x[0]}</span><small>${x[2]}</small></div><strong>${x[1]}</strong><b>›</b></div>`).join('')}</section></div>`;}
function trainingView(){const t=data.training,tsb=[1.86,1.91,1.88,1.73,1.62,1.66,1.59,1.70],atl=[41,46,49,45,44,52,53,t.atl],ctl=[22,24,25,27,28,30,31,t.ctl];return `<div class="training-pro-page fade-in"><div class="page-intro"><span class="eyebrow">TRAINING LOAD</span><h2>훈련 부하</h2><p>피로와 피트니스의 균형을 추적합니다.</p></div><section class="load-warning"><span>◌</span><p><b>주의가 필요합니다.</b> 최근 피로가 높아 회복 시간을 충분히 확보하는 편이 좋습니다.</p><strong>⌄</strong></section><section class="load-kpis"><div><span>TSB</span><strong class="red">${t.tsb}</strong><small>주의</small></div><div><span>피로 (ATL)</span><strong class="pink">${t.atl}</strong><small>단기 부하</small></div><div><span>피트니스 (CTL)</span><strong class="blue">${t.ctl}</strong><small>장기 부하</small></div></section><section class="load-chart-card"><div class="chart-heading"><h2>부하 균형</h2><span>30일</span></div>${lineChart(tsb,{color:'#ef554f',height:180,rightAxis:true,labels:['','','','','','','','']})}<div class="load-legend"><span><i class="red-dot"></i>주의</span><span><i class="yellow-dot"></i>과부하</span><span><i class="green-dot"></i>최적</span><span><i class="blue-dot"></i>비활성</span></div></section><section class="load-chart-card"><div class="chart-heading"><h2>피로 · 피트니스</h2><span>${detailDate}</span></div><div class="dual-lines">${lineChart(atl,{color:'#f34edc',height:185,rightAxis:true,labels:['','','','','','','','']})}<div class="overlay-blue">${lineChart(ctl,{color:'#478cff',height:185,rightAxis:true,labels:['','','','','','','','']})}</div></div><div class="load-legend"><span><i class="pink-dot"></i>피로 (ATL)</span><span><i class="blue-dot"></i>피트니스 (CTL)</span><span><i class="band-dot"></i>권장 범위</span></div><div class="period-control four"><button class="active">30일</button><button>60일</button><button>180일</button><button>연간</button></div></section><section class="training-mini-grid"><div><span>훈련 부하 중점</span><strong>${t.focusLow}%</strong><small>저강도 중심</small></div><div><span>심박 회복</span><strong>${t.hrRecovery}</strong><small>BPM</small></div></section></div>`;}
function workoutView(){return `<div class="fade-in"><div class="page-intro"><span class="eyebrow">STRENGTH</span><h2>근력운동</h2><p>최근 기록과 수행 추세</p></div><section class="workout-block"><button class="workout-cta" id="startWorkout">+ 근력운동 기록</button><h3>최근 운동</h3>${(data.strength.recent||[]).map(x=>`<div class="list-row"><div><strong>${x.name}</strong><div class="meta">${x.date}</div></div><span>${x.summary}</span></div>`).join('')||'<div class="empty">최근 기록 없음</div>'}</section><section class="workout-block"><h3>Apps Script 연동</h3><input id="gasInput" class="input-dark" value="${getGasUrl()}" placeholder="Apps Script /exec URL"><button class="soft-btn full" id="saveGas">연동 URL 저장</button></section></div>`;}
function journalView(){return renderNutrition(data,nutritionChartKey);}
function detailView(key){if(key==='stress')return stressView();if(key==='energy')return energyView();if(key==='training')return trainingIntensityView();if(key==='sleep')return sleepView();return recoveryView();}
function render(){const isDetail=route.startsWith('detail:');document.querySelector('.app-header')?.classList.toggle('hidden-on-detail',isDetail);document.querySelector('.bottom-nav')?.classList.toggle('hidden-on-detail',isDetail);document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.route===route));title.textContent=route==='today'?'오늘':route==='health'?'건강':route==='journal'?'기록':route==='workout'?'운동':route==='training'?'트레이닝':'상세';main.classList.toggle('detail-main',isDetail);main.innerHTML=route==='today'?todayView():route==='health'?healthView():route==='journal'?journalView():route==='workout'?workoutView():route==='training'?trainingView():isDetail?detailView(route.split(':')[1]):todayView();bindDynamic();}
function bindDynamic(){main.querySelectorAll('[data-detail]').forEach(el=>el.addEventListener('click',()=>{route=`detail:${el.dataset.detail}`;render();window.scrollTo({top:0,behavior:'instant'});}));main.querySelectorAll('[data-back]').forEach(el=>el.addEventListener('click',()=>{route='today';render();window.scrollTo({top:0,behavior:'instant'});}));main.querySelectorAll('[data-route-go]').forEach(el=>el.addEventListener('click',()=>{route=el.dataset.routeGo;render();window.scrollTo({top:0,behavior:'instant'});}));main.querySelector('#saveGas')?.addEventListener('click',()=>{setGasUrl(main.querySelector('#gasInput').value);alert('연동 URL을 저장했습니다.');});main.querySelector('#startWorkout')?.addEventListener('click',()=>alert('근력운동 입력 화면은 다음 구현 단계에서 기존 기록 시스템과 연결합니다.'));if(route==='journal')bindNutrition(main,data,{onDataChange:d=>{data=d;render();},onChartKey:k=>{nutritionChartKey=k;render();}});}
document.querySelectorAll('.nav-item').forEach(el=>el.addEventListener('click',()=>{route=el.dataset.route;render();window.scrollTo({top:0,behavior:'instant'});}));
syncBtn.addEventListener('click',async()=>{syncBtn.disabled=true;syncBtn.classList.add('spin');data=await refreshRemote();render();syncBtn.classList.remove('spin');syncBtn.disabled=false;});
render();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));