import {loadDashboard,refreshRemote,getGasUrl,setGasUrl} from './data-source.js';

const main=document.getElementById('appMain');
const title=document.getElementById('pageTitle');
const dateLabel=document.getElementById('dateLabel');
const syncBtn=document.getElementById('syncBtn');
let data=await loadDashboard();
let route='today';

const fmtMin=m=>`${Math.floor(m/60)}시간${m%60?`${m%60}분`:''}`;
const pct=n=>`${Math.round(n)}%`;
const todayText=new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'long'}).format(new Date());
const dayLabels=['8/31','9/1','9/2','9/3','9/4','9/5','오늘'];
dateLabel.textContent=todayText;

function spark(values,color='#55b8e6'){
  const w=180,h=66,p=5,min=Math.min(...values),max=Math.max(...values),r=(max-min)||1;
  const pts=values.map((v,i)=>({x:p+i*(w-2*p)/(values.length-1),y:h-p-(v-min)*(h-2*p)/r,v}));
  const id=`g${Math.random().toString(36).slice(2)}`;
  const area=`M ${pts[0].x} ${h-p} L ${pts.map(x=>`${x.x} ${x.y}`).join(' L ')} L ${pts.at(-1).x} ${h-p} Z`;
  return `<svg class="mini-line" viewBox="0 0 ${w} ${h}" aria-hidden="true"><defs><linearGradient id="${id}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${color}" stop-opacity=".32"/><stop offset="1" stop-color="${color}" stop-opacity="0"/></linearGradient></defs><path d="${area}" fill="url(#${id})"/><polyline points="${pts.map(x=>`${x.x},${x.y}`).join(' ')}" fill="none" stroke="${color}" stroke-width="3.2" stroke-linecap="round" stroke-linejoin="round"/><circle cx="${pts.at(-1).x}" cy="${pts.at(-1).y}" r="7" fill="${color}" opacity=".16"/><circle cx="${pts.at(-1).x}" cy="${pts.at(-1).y}" r="3.8" fill="${color}" stroke="#111" stroke-width="2"/></svg>`;
}

function segmentedGauge(value,type='recovery',targetMin=null,targetMax=null){
  const marker=Math.max(1,Math.min(99,value));
  const target=targetMin!=null?`<span class="target-band" style="left:${targetMin}%;width:${Math.max(0,targetMax-targetMin)}%"></span>`:'';
  return `<div class="score-scale ${type}">${target}<div class="scale-segments"><i></i><i></i><i></i><i></i><i></i></div><b class="scale-marker" style="left:${marker}%"><em>${Math.round(value)}</em></b><div class="scale-labels"><span>0</span><span>25</span><span>50</span><span>75</span><span>100</span></div></div>`;
}

function richLineChart(values,{color='#55b8e6',unit='',baseline=null,labels=dayLabels,minY=null,maxY=null}={}){
  const w=360,h=235,l=38,rp=10,t=20,b=34;
  const rawMin=minY??Math.min(...values,baseline??Infinity), rawMax=maxY??Math.max(...values,baseline??-Infinity);
  const pad=Math.max(1,(rawMax-rawMin)*.22); const min=rawMin-pad,max=rawMax+pad,range=(max-min)||1;
  const X=i=>l+i*(w-l-rp)/(values.length-1), Y=v=>t+(max-v)*(h-t-b)/range;
  const pts=values.map((v,i)=>({x:X(i),y:Y(v),v})); const id=`area${Math.random().toString(36).slice(2)}`;
  const ticks=[max,(max+min)/2,min].map(v=>Math.round(v*10)/10);
  const area=`M ${pts[0].x} ${h-b} L ${pts.map(p=>`${p.x} ${p.y}`).join(' L ')} L ${pts.at(-1).x} ${h-b} Z`;
  return `<svg class="chart-svg detailed" viewBox="0 0 ${w} ${h}" role="img"><defs><linearGradient id="${id}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${color}" stop-opacity=".30"/><stop offset="1" stop-color="${color}" stop-opacity="0"/></linearGradient></defs>${ticks.map(v=>`<line x1="${l}" y1="${Y(v)}" x2="${w-rp}" y2="${Y(v)}" class="grid-line"/><text x="2" y="${Y(v)+4}" class="axis-label">${v}${unit}</text>`).join('')}${baseline!=null?`<line x1="${l}" y1="${Y(baseline)}" x2="${w-rp}" y2="${Y(baseline)}" class="baseline-line"/><text x="${w-rp-2}" y="${Y(baseline)-6}" text-anchor="end" class="baseline-text">기준 ${baseline}${unit}</text>`:''}<path d="${area}" fill="url(#${id})"/><polyline points="${pts.map(p=>`${p.x},${p.y}`).join(' ')}" fill="none" stroke="${color}" stroke-width="3.4" stroke-linecap="round" stroke-linejoin="round"/>${pts.map((p,i)=>`<circle cx="${p.x}" cy="${p.y}" r="${i===pts.length-1?4.8:3}" fill="${color}" stroke="#111318" stroke-width="2"/>`).join('')}${labels.slice(0,values.length).map((x,i)=>`<text x="${X(i)}" y="${h-8}" text-anchor="middle" class="x-label">${x}</text>`).join('')}<g class="last-value"><rect x="${Math.min(w-72,pts.at(-1).x-29)}" y="${Math.max(4,pts.at(-1).y-34)}" rx="9" width="58" height="24"/><text x="${Math.min(w-43,pts.at(-1).x)}" y="${Math.max(20,pts.at(-1).y-18)}" text-anchor="middle">${pts.at(-1).v}${unit}</text></g></svg>`;
}

function sleepStages(){
  const s=data.today.sleep; const awake=Math.max(18,Math.round(s.minutes*.045)); const core=Math.max(0,s.minutes-s.deep-s.rem);
  const total=awake+core+s.deep+s.rem;
  const parts=[['깨어있음',awake,'#ff755f'],['REM',s.rem,'#9e66ff'],['코어',core,'#4f7dff'],['깊은 수면',s.deep,'#3155b8']];
  return `<div class="sleep-stage-wrap"><div class="stage-bar">${parts.map(x=>`<span style="width:${x[1]/total*100}%;background:${x[2]}"></span>`).join('')}</div><div class="stage-legend">${parts.map(x=>`<div><i style="background:${x[2]}"></i><span>${x[0]}</span><strong>${x[1]}분</strong></div>`).join('')}</div></div>`;
}

function metricCard(key,label,value,status,visual,glow,statusColor){return `<button class="metric-card" data-detail="${key}" style="--card-glow:${glow};--status:${statusColor}"><div class="metric-title">${label}</div><div class="metric-visual">${visual}</div><div class="metric-value-row"><strong class="metric-value">${value}</strong><span class="metric-status">${status}</span></div></button>`;}

function todayView(){const t=data.today;return `<div class="fade-in"><section class="hero"><div class="suggestion"><div class="kicker">✦ 오늘의 제안</div><p>회복 ${t.recovery.score}% · 수면 ${t.sleep.quality}%입니다. 현재 상태에서는 목표 강도 ${t.training.targetMin}–${t.training.targetMax}% 안에서 훈련하는 편이 적절합니다.</p></div></section><div class="overview-title"><h2>오늘의 상태</h2><span>${new Date(data.updatedAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</span></div><section class="metric-grid">${metricCard('recovery','회복',pct(t.recovery.score),t.recovery.status,spark(t.recovery.trend,'#29cbd8'),'#1fd0da','#45d7df')}${metricCard('stress','스트레스',pct(t.stress.score),t.stress.status,segmentedGauge(t.stress.score,'stress'),'#6c5bf0','#8980ff')}${metricCard('energy','신체 에너지',pct(t.energy.score),t.energy.status,segmentedGauge(t.energy.score,'energy'),'#23d16f','#ffb02e')}${metricCard('training','운동 강도',pct(t.training.score),t.training.status,segmentedGauge(t.training.score,'training',t.training.targetMin,t.training.targetMax),'#b13d7e','#7385ff')}</section><button class="section-card sleep-card" data-detail="sleep"><div class="sleep-head"><h2>수면</h2><span class="score">품질 ${t.sleep.quality}% ›</span></div>${sleepStages()}<div class="big-row"><strong>${fmtMin(t.sleep.minutes)}</strong><span class="subtle">목표 ${fmtMin(t.sleep.targetMinutes)}</span></div></button><section class="section-card"><div class="sleep-head"><h2>신체 지표</h2><span class="score">최근값</span></div><div class="vitals"><div class="vital"><span>HRV</span><strong>${t.vitals.hrv} ms</strong><small>양호</small></div><div class="vital"><span>안정 시 심박</span><strong>${t.vitals.rhr} bpm</strong><small>낮음</small></div><div class="vital"><span>SpO₂</span><strong>${t.vitals.spo2}%</strong><small>정상</small></div></div></section></div>`;}

const detailConfig={
 recovery:{label:'회복',className:'recovery',score:d=>d.today.recovery.score,status:d=>d.today.recovery.status,range:d=>'오늘 상태',rangeValue:d=>`${d.today.recovery.score}%`,comparisons:d=>[['오늘 평균 HRV',`${d.today.recovery.hrv} ms`,`14일 평균 ${d.today.recovery.hrvBaseline} ms`],['안정 시 심박',`${d.today.recovery.rhr} bpm`,`14일 평균 ${d.today.recovery.rhrBaseline} bpm`]],trend:d=>d.today.recovery.trend,baseline:d=>d.today.recovery.hrvBaseline,unit:'',insight:d=>'HRV는 기준선보다 높고 안정 시 심박은 낮은 편입니다. 회복 상태는 양호한 방향입니다.'},
 stress:{label:'스트레스',className:'stress',score:d=>d.today.stress.score,status:d=>d.today.stress.status,range:d=>'오늘 평균',rangeValue:d=>`${d.today.stress.avg}%`,comparisons:d=>[['평균 스트레스',`${d.today.stress.avg}%`,`14일 평균 ${d.today.stress.avgBaseline}%`],['안정 시 심박',`${d.today.stress.rhr} bpm`,`기준 ${d.today.recovery.rhrBaseline} bpm`]],trend:d=>d.today.stress.trend,baseline:d=>d.today.stress.avgBaseline,unit:'%',insight:d=>'스트레스는 HRV·심박·수면·최근 훈련 부하를 조합한 MVP 추정치입니다.'},
 energy:{label:'신체 에너지',className:'energy',score:d=>d.today.energy.score,status:d=>d.today.energy.status,range:d=>'오늘 범위',rangeValue:d=>`${d.today.energy.rangeMin}%–${d.today.energy.rangeMax}%`,comparisons:d=>[['야간 충전',`${d.today.energy.overnightCharge}%`,'수면 기반 회복량'],['주간 소모',`${d.today.energy.dayDrain}%`,'활동·운동 기반']],trend:d=>d.today.energy.trend,baseline:d=>null,unit:'%',insight:d=>`현재 신체 에너지는 ${d.today.energy.score}%이며, 오늘 최고 ${d.today.energy.rangeMax}%에서 점차 소모된 상태입니다.`},
 training:{label:'운동 강도',className:'training',score:d=>d.today.training.score,status:d=>d.today.training.status,range:d=>'오늘 목표 범위',rangeValue:d=>`${d.today.training.targetMin}%–${d.today.training.targetMax}%`,comparisons:d=>[['회복',`${d.today.training.recovery}%`,'오늘 상태 반영'],['소모 칼로리',`${d.today.training.calories} kcal`,'활동 에너지']],trend:d=>[12,21,18,34,27,31,d.today.training.score],baseline:d=>null,unit:'%',insight:d=>'오늘 목표 운동 강도 범위와 현재 누적 강도를 함께 비교합니다.'},
 sleep:{label:'수면',className:'sleep',score:d=>d.today.sleep.quality,status:d=>'수면 품질',range:d=>'총 수면',rangeValue:d=>fmtMin(d.today.sleep.minutes),comparisons:d=>[['수면 시간',fmtMin(d.today.sleep.minutes),`목표 ${fmtMin(d.today.sleep.targetMinutes)}`],['수면 효율',`${d.today.sleep.efficiency}%`,`규칙성 ${d.today.sleep.consistency}%`]],trend:d=>[64,71,67,75,69,72,d.today.sleep.quality],baseline:d=>d.today.sleep.avg14Quality,unit:'%',insight:d=>`깊은 수면 ${d.today.sleep.deep}분, REM ${d.today.sleep.rem}분입니다.`}
};

function qualityRows(){const s=data.today.sleep;const rows=[['총 수면','◷',Math.min(100,s.minutes/s.targetMinutes*100),fmtMin(s.minutes),'#55a7ff'],['회복 수면','◉',Math.min(100,(s.deep+s.rem)/210*100),`${s.deep+s.rem}분`,'#8a48ee'],['연속성','⌁',76,'보통','#27c9c5'],['효율성','◔',s.efficiency,`${s.efficiency}%`,'#2386ff'],['규칙성','◎',s.consistency,`${s.consistency}%`,'#a64ae6']];return `<div class="quality-list">${rows.map(r=>`<div class="quality-row"><div class="quality-icon" style="color:${r[4]}">${r[1]}</div><div class="quality-main"><span>${r[0]}</span><div class="mini-progress detailed"><i style="width:${r[2]}%;--q:${r[4]}"></i><b style="left:80%"></b></div></div><div class="quality-value">${r[3]} ›</div></div>`).join('')}</div>`;}

function detailView(key){const c=detailConfig[key];if(!c)return todayView();const score=c.score(data),comps=c.comparisons(data);const bar=segmentedGauge(score,key==='training'?'training':key,key==='training'?data.today.training.targetMin:null,key==='training'?data.today.training.targetMax:null);return `<div class="detail-page fade-in"><div class="detail-topbar"><button class="circle-action" data-back>‹</button><div class="center"><strong>${c.label}</strong><span>${todayText}</span></div><button class="circle-action">···</button></div><section class="detail-hero ${c.className}"><div class="detail-score">${score}<span>%</span></div><div class="detail-status">${c.status(data)}</div><div class="detail-range"><span>${c.range(data)}</span><strong>${c.rangeValue(data)}</strong></div>${bar}</section><div class="detail-content"><section class="comparison-grid">${comps.map((x,i)=>`<div class="compare" style="--comp:${i?'#6f7cff':'#42d195'}"><span>${x[0]}</span><strong>${x[1]}</strong><em>${x[2]}</em></div>`).join('')}</section><div class="update-line">마지막 업데이트 ${new Date(data.updatedAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</div><div class="insight">${c.insight(data)}</div>${key==='sleep'?`<section class="detail-section"><div class="detail-section-title"><h2>수면 단계</h2><span class="subtle">ⓘ</span></div><div class="chart-card">${sleepStages()}</div></section><section class="detail-section"><div class="detail-section-title"><h2>수면 품질 차원</h2></div>${qualityRows()}</section>`:`<section class="detail-section"><div class="detail-section-title"><h2>최근 7일 추세</h2><span class="subtle">ⓘ</span></div><div class="chart-card">${richLineChart(c.trend(data),{color:key==='stress'?'#7477ff':key==='energy'?'#39d17e':key==='training'?'#d34b91':'#39cbd6',unit:c.unit,baseline:c.baseline(data)})}</div></section>`}</div></div>`;}

function healthView(){const v=data.today.vitals;const cards=[['VO₂ Max',v.vo2max,'정상'],['HRV',`${v.hrv} ms`,'정상'],['안정 시 심박',`${v.rhr} bpm`,'낮음'],['호흡수',`${v.resp} BrPM`,'정상'],['혈중 산소',`${v.spo2}%`,'정상'],['체중',`${v.weight} kg`,'증가'],['BMI',v.bmi,'과체중'],['체지방률',`${v.bodyFat}%`,'약간 높음']];return `<div class="fade-in"><div class="screen-title"><div><h2>건강</h2><p>심폐·회복·체성분 지표</p></div></div><section class="feature-hero" style="--fh:#5c5fff"><div class="hero-label">생체 나이</div><div class="hero-number">39.0</div><div class="hero-status">실제 나이 대비 +0.4세</div>${segmentedGauge(58,'health')}</section><section class="health-grid">${cards.map((x,i)=>`<div class="health-card"><span class="label">${x[0]}</span><strong>${x[1]}</strong><div class="micro-track"><i style="width:${45+i*5}%"></i></div><div class="state">${x[2]}</div></div>`).join('')}</section><section class="section-card"><h2>최근 HRV</h2>${richLineChart(data.today.recovery.trend,{color:'#39cbd6',baseline:data.today.recovery.hrvBaseline,unit:''})}</section></div>`;}

function journalView(){return `<div class="fade-in"><div class="screen-title"><div><h2>기록</h2><p>상태 변화와 분석 이력</p></div></div><section class="feature-hero" style="--fh:#8b47ee"><div class="hero-label">오늘 요약</div><div class="hero-number">${data.today.recovery.score}%</div><div class="hero-status">회복 ${data.today.recovery.status}</div>${spark(data.today.recovery.trend,'#9b74ff')}</section><section class="journal-card"><h3>오늘 상태</h3><div class="list"><div class="list-row"><div>회복<div class="meta">HRV ${data.today.recovery.hrv}ms · RHR ${data.today.recovery.rhr}bpm</div></div><span class="pill">${data.today.recovery.score}%</span></div><div class="list-row"><div>수면<div class="meta">${fmtMin(data.today.sleep.minutes)} · 품질 ${data.today.sleep.quality}%</div></div><span class="pill">자동</span></div><div class="list-row"><div>저널 태그 영향 분석<div class="meta">Pro 검증 후 상관분석 기능 추가</div></div><span class="pill">2차</span></div></div></section></div>`;}

function workoutView(){const recent=data.strength.recent||[];return `<div class="fade-in"><div class="screen-title"><div><h2>운동</h2><p>근력운동 기록과 최근 수행</p></div></div><section class="feature-hero" style="--fh:#ff9b3d"><div class="hero-label">이번 주 근력운동</div><div class="hero-number">3회</div><div class="hero-status">최근 기록 기준</div><div class="week-bars">${[42,76,18,65,88,30,54].map((x,i)=>`<i style="height:${x}%"><span>${['월','화','수','목','금','토','일'][i]}</span></i>`).join('')}</div></section><section class="workout-block"><button class="workout-cta" id="startWorkout">+ 근력운동 기록</button></section><section class="workout-block"><h3>최근 기록</h3><div class="list">${recent.map(x=>`<div class="list-row"><div><strong>${x.name}</strong><div class="meta">${x.date}</div></div><div class="right-summary">${x.summary}</div></div>`).join('')||'<div class="empty">최근 기록 없음</div>'}</div></section><section class="workout-block"><h3>연동 설정</h3><input id="gasInput" class="input-dark" type="url" placeholder="Apps Script /exec URL" value="${getGasUrl()}"><button id="saveGas" class="workout-cta secondary">연동 URL 저장</button></section></div>`;}

function zoneRows(){const z=[['Z1','회복',36,'#5b7fff'],['Z2','저강도',34,'#27c7c5'],['Z3','중강도',19,'#3bd06f'],['Z4','고강도',8,'#f2b93b'],['Z5','최고강도',3,'#ff5d62']];return `<div class="zone-table">${z.map(x=>`<div class="zone-row"><div class="zone-name"><b>${x[0]}</b><span>${x[1]}</span></div><div class="zone-track detailed"><i style="width:${x[2]}%;background:${x[3]}"></i><b style="left:50%"></b></div><strong>${x[2]}%</strong></div>`).join('')}</div>`;}

function trainingView(){const t=data.training;const tsb=[-6,-3,1,4,2,0,t.tsb];return `<div class="fade-in"><div class="screen-title"><div><h2>트레이닝</h2><p>훈련 부하와 회복 균형</p></div></div><section class="training-block"><h3>훈련 부하</h3><div class="load-hero"><div class="load-stat"><span>TSB</span><strong>${t.tsb}</strong><small>현재 균형</small></div><div class="load-stat"><span>ATL</span><strong>${t.atl}</strong><small>급성 부하</small></div><div class="load-stat"><span>CTL</span><strong>${t.ctl}</strong><small>만성 부하</small></div></div><div class="chart-card compact">${richLineChart(tsb,{color:'#78a6ff',baseline:0,labels:dayLabels,unit:''})}</div></section><section class="training-block"><h3>운동 중 심박수 구간</h3>${zoneRows()}<div class="zone-axis"><span>낮음</span><span>중간</span><span>높음</span></div></section><section class="training-block"><h3>훈련 부하 중점</h3><div class="focus-stack"><i style="width:${t.focusLow}%;background:#39cb72"></i><i style="width:${t.focusHigh}%;background:#f2b943"></i><i style="width:${t.focusAnaerobic}%;background:#ff5d62"></i></div><div class="focus-legend"><span><i style="background:#39cb72"></i>저강도 ${t.focusLow}%</span><span><i style="background:#f2b943"></i>고강도 ${t.focusHigh}%</span><span><i style="background:#ff5d62"></i>무산소 ${t.focusAnaerobic}%</span></div></section><section class="training-block"><h3>운동 후 심박수 회복</h3><div class="recovery-drop"><strong>${t.hrRecovery}</strong><span>BPM</span><div class="drop-viz"><i></i><b>1분 후 감소폭</b></div></div></section></div>`;}

function render(){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.route===route));title.textContent=route==='today'?'오늘':({health:'건강',journal:'기록',workout:'운동',training:'트레이닝'})[route]||'상세';main.innerHTML=route==='today'?todayView():route==='health'?healthView():route==='journal'?journalView():route==='workout'?workoutView():route==='training'?trainingView():route.startsWith('detail:')?detailView(route.split(':')[1]):todayView();bindDynamic();}
function bindDynamic(){main.querySelectorAll('[data-detail]').forEach(el=>el.addEventListener('click',()=>{route=`detail:${el.dataset.detail}`;render();}));main.querySelector('[data-back]')?.addEventListener('click',()=>{route='today';render();});main.querySelector('#saveGas')?.addEventListener('click',()=>{setGasUrl(main.querySelector('#gasInput').value);alert('연동 URL을 저장했습니다.');});main.querySelector('#startWorkout')?.addEventListener('click',()=>alert('근력운동 입력 폼은 다음 데이터 연결 단계에서 이식합니다.'));}
document.querySelectorAll('.nav-item').forEach(el=>el.addEventListener('click',()=>{route=el.dataset.route;render();}));
syncBtn.addEventListener('click',async()=>{syncBtn.disabled=true;syncBtn.textContent='…';data=await refreshRemote();render();syncBtn.textContent='↻';syncBtn.disabled=false;});
render();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
