import {loadDashboard,refreshRemote,getGasUrl,setGasUrl,nutritionSummary} from './data-source.js';
import {renderNutrition,bindNutrition} from './nutrition-ui.js';

const main=document.getElementById('appMain');
const title=document.getElementById('pageTitle');
const dateLabel=document.getElementById('dateLabel');
const syncBtn=document.getElementById('syncBtn');
let data=await loadDashboard();
let route='today';
let nutritionChartKey='kcal';
const todayText=new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'long'}).format(new Date());
dateLabel.textContent=todayText;

const fmtMin=m=>`${Math.floor(m/60)}시간 ${m%60}분`;
const clamp=(v,a=0,b=100)=>Math.min(b,Math.max(a,v));

function smoothPath(points){if(points.length<2)return'';let d=`M ${points[0].x} ${points[0].y}`;for(let i=0;i<points.length-1;i++){const p0=points[i-1]||points[i],p1=points[i],p2=points[i+1],p3=points[i+2]||p2;d+=` C ${p1.x+(p2.x-p0.x)/6} ${p1.y+(p2.y-p0.y)/6}, ${p2.x-(p3.x-p1.x)/6} ${p2.y-(p3.y-p1.y)/6}, ${p2.x} ${p2.y}`;}return d;}
function proChart(values,{color='#5fd5df',baseline=null,unit='',labels=['월','화','수','목','금','토','오늘'],height=220}={}){const w=360,h=height,l=40,r=14,t=26,b=34;base=[...values];if(baseline!=null)base.push(baseline);const rawMin=Math.min(...base),rawMax=Math.max(...base),pad=Math.max(2,(rawMax-rawMin)*.18),min=rawMin-pad,max=rawMax+pad,range=max-min||1,X=i=>l+i*(w-l-r)/(values.length-1),Y=v=>t+(max-v)*(h-t-b)/range,pts=values.map((v,i)=>({x:X(i),y:Y(v),v})),path=smoothPath(pts),area=`${path} L ${pts.at(-1).x} ${h-b} L ${pts[0].x} ${h-b} Z`,id=`g-${Math.random().toString(36).slice(2)}`,ticks=[max,max-range/3,max-range*2/3,min];return `<svg class="pro-chart" viewBox="0 0 ${w} ${h}"><defs><linearGradient id="${id}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${color}" stop-opacity=".28"/><stop offset="1" stop-color="${color}" stop-opacity="0"/></linearGradient></defs>${ticks.map(v=>`<line x1="${l}" x2="${w-r}" y1="${Y(v)}" y2="${Y(v)}" class="chart-grid"/><text x="4" y="${Y(v)+3}" class="chart-axis">${Math.round(v*10)/10}${unit}</text>`).join('')}${baseline!=null?`<line x1="${l}" x2="${w-r}" y1="${Y(baseline)}" y2="${Y(baseline)}" class="chart-baseline"/>`:''}<path d="${area}" fill="url(#${id})"/><path d="${path}" fill="none" stroke="${color}" stroke-width="3.4" stroke-linecap="round"/>${labels.slice(0,values.length).map((v,i)=>`<text x="${X(i)}" y="${h-8}" text-anchor="middle" class="chart-x">${v}</text>`).join('')}<circle cx="${pts.at(-1).x}" cy="${pts.at(-1).y}" r="4.5" fill="${color}" stroke="#0b0c0f" stroke-width="2"/></svg>`;}
function ring(value,color,label){const r=40,c=2*Math.PI*r,d=c*clamp(value)/100;return `<div class="ring-wrap"><svg viewBox="0 0 100 100"><circle class="ring-track" cx="50" cy="50" r="40"/><circle class="ring-value" cx="50" cy="50" r="40" style="stroke:${color};stroke-dasharray:${d} ${c-d}"/></svg><div class="ring-center"><strong>${Math.round(value)}<small>%</small></strong><span>${label}</span></div></div>`;}
function rangeBar(value,{type='recovery',targetMin=null,targetMax=null}={}){return `<div class="range-viz ${type}"><div class="range-track">${targetMin!=null?`<i class="target" style="left:${targetMin}%;width:${targetMax-targetMin}%"></i>`:''}<b class="cursor" style="left:${clamp(value)}%"><span>${Math.round(value)}</span></b></div><div class="range-labels"><span>낮음</span><span>보통</span><span>양호</span><span>높음</span></div></div>`;}
function metricCard(key,label,score,status,color,visual){return `<button class="metric-card premium" data-detail="${key}" style="--accent:${color}"><div class="metric-head"><span>${label}</span><span>›</span></div><div class="metric-art">${visual}</div><div class="metric-foot"><strong>${Math.round(score)}<small>%</small></strong><span>${status}</span></div></button>`;}
function sleepTimeline(){const s=data.today.sleep,blocks=[['깊음',17,'#3458ca'],['코어',26,'#5176ff'],['REM',11,'#a063ff'],['코어',21,'#5176ff'],['깊음',9,'#3458ca'],['코어',8,'#5176ff'],['REM',6,'#a063ff'],['깨어남',2,'#ff786b']];return `<div class="sleep-timeline"><div class="sleep-hours"><span>23:00</span><span>02:00</span><span>05:00</span><span>08:00</span></div><div class="sleep-lanes">${blocks.map(x=>`<i style="width:${x[1]}%;background:${x[2]}"></i>`).join('')}</div><div class="sleep-legend"><span><i style="background:#a063ff"></i>REM ${s.rem}분</span><span><i style="background:#5176ff"></i>코어</span><span><i style="background:#3458ca"></i>깊음 ${s.deep}분</span></div></div>`;}

function todayNutritionCard(){const s=nutritionSummary(data);const g=s.goals;return `<section class="nutrition-card"><div class="card-head"><div><span class="eyebrow">NUTRITION</span><h2>오늘의 식단</h2></div><button class="soft-btn" data-route-go="journal">기록</button></div><div class="calorie-row"><div><strong>${Math.round(s.kcal).toLocaleString()}</strong><span>/ ${g.kcal.toLocaleString()} kcal</span></div><div class="calorie-progress"><i style="width:${clamp(s.kcal/g.kcal*100)}%"></i></div></div><div class="body-strip" style="margin-top:12px"><div><span>단백질</span><strong>${Math.round(s.protein)}<small> / ${g.protein}g</small></strong></div><div><span>탄수화물</span><strong>${Math.round(s.carbs)}<small> / ${g.carbs}g</small></strong></div><div><span>지방</span><strong>${Math.round(s.fat)}<small> / ${g.fat}g</small></strong></div></div></section>`;}

function todayView(){const t=data.today;return `<div class="fade-in"><section class="hero-command"><div><span class="eyebrow">DAILY READINESS</span><h2>오늘 컨디션은 <b>좋은 편</b>입니다</h2><p>회복은 충분하지만 운동 강도는 아직 목표 범위보다 낮습니다.</p></div><div class="hero-rings">${ring(t.recovery.score,'#5bd7df','회복')}${ring(t.sleep.quality,'#8a6dff','수면')}</div></section><div class="section-label"><h2>오늘의 상태</h2><span>${new Date(data.updatedAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</span></div><section class="metric-grid">${metricCard('recovery','회복',t.recovery.score,t.recovery.status,'#5bd7df',proChart(t.recovery.trend,{color:'#5bd7df',height:110,labels:['','','','','','','']}))}${metricCard('stress','스트레스',t.stress.score,t.stress.status,'#7f73ff',rangeBar(t.stress.score,{type:'stress'}))}${metricCard('energy','신체 에너지',t.energy.score,t.energy.status,'#51d485',rangeBar(t.energy.score,{type:'energy'}))}${metricCard('training','운동 강도',t.training.score,t.training.status,'#d764aa',rangeBar(t.training.score,{type:'training',targetMin:t.training.targetMin,targetMax:t.training.targetMax}))}</section><button class="sleep-premium" data-detail="sleep"><div class="card-head"><div><span class="eyebrow">SLEEP</span><h2>${fmtMin(t.sleep.minutes)}</h2></div><div class="sleep-score"><strong>${t.sleep.quality}</strong><span>품질</span></div></div>${sleepTimeline()}</button>${todayNutritionCard()}<section class="body-strip"><div><span>HRV</span><strong>${t.vitals.hrv}<small> ms</small></strong></div><div><span>안정 시 심박</span><strong>${t.vitals.rhr}<small> bpm</small></strong></div><div><span>SpO₂</span><strong>${t.vitals.spo2}<small>%</small></strong></div></section></div>`;}

const cfg={recovery:{label:'회복',color:'#5bd7df',score:d=>d.today.recovery.score,status:d=>d.today.recovery.status,trend:d=>d.today.recovery.trend,baseline:d=>d.today.recovery.hrvBaseline,unit:'',facts:d=>[['HRV',`${d.today.recovery.hrv} ms`,`기준 ${d.today.recovery.hrvBaseline} ms`],['안정 시 심박',`${d.today.recovery.rhr} bpm`,`기준 ${d.today.recovery.rhrBaseline} bpm`]]},stress:{label:'스트레스',color:'#8075ff',score:d=>d.today.stress.score,status:d=>d.today.stress.status,trend:d=>d.today.stress.trend,baseline:d=>d.today.stress.avgBaseline,unit:'%',facts:d=>[['평균 스트레스',`${d.today.stress.avg}%`,`14일 ${d.today.stress.avgBaseline}%`],['안정 시 심박',`${d.today.stress.rhr} bpm`,'심박 반응']]},energy:{label:'신체 에너지',color:'#50d287',score:d=>d.today.energy.score,status:d=>d.today.energy.status,trend:d=>d.today.energy.trend,baseline:d=>null,unit:'%',facts:d=>[['야간 충전',`${d.today.energy.overnightCharge}%`,'수면 기반'],['주간 소모',`${d.today.energy.dayDrain}%`,'활동 기반']]},training:{label:'운동 강도',color:'#d764aa',score:d=>d.today.training.score,status:d=>d.today.training.status,trend:d=>[12,21,18,34,27,31,d.today.training.score],baseline:d=>null,unit:'%',facts:d=>[['권장 범위',`${d.today.training.targetMin}–${d.today.training.targetMax}%`,'회복 상태 반영'],['활동 에너지',`${d.today.training.calories} kcal`,'오늘 누적']]}};
function detailView(key){if(key==='sleep')return sleepView();const c=cfg[key],score=c.score(data);return `<div class="detail-premium fade-in" style="--accent:${c.color}"><div class="detail-nav"><button data-back>‹</button><div><strong>${c.label}</strong><span>${todayText}</span></div><button>···</button></div><section class="score-hero"><div class="score-copy"><span class="eyebrow">TODAY</span><strong>${score}<small>%</small></strong><h2>${c.status(data)}</h2></div>${ring(score,c.color,c.label)}</section><section class="facts-grid">${c.facts(data).map(x=>`<div><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('')}</section><section class="analysis-card"><div class="analysis-title"><div><span class="eyebrow">7 DAY TREND</span><h2>최근 추세</h2></div></div>${proChart(c.trend(data),{color:c.color,baseline:c.baseline(data),unit:c.unit})}</section></div>`;}
function sleepView(){const s=data.today.sleep;return `<div class="detail-premium fade-in" style="--accent:#8a6dff"><div class="detail-nav"><button data-back>‹</button><div><strong>수면</strong><span>${todayText}</span></div><button>···</button></div><section class="score-hero"><div class="score-copy"><span class="eyebrow">LAST NIGHT</span><strong>${s.quality}<small>%</small></strong><h2>${fmtMin(s.minutes)}</h2></div>${ring(s.quality,'#8a6dff','품질')}</section><section class="analysis-card"><div class="analysis-title"><div><span class="eyebrow">SLEEP STAGES</span><h2>수면 단계</h2></div></div>${sleepTimeline()}</section><section class="facts-grid"><div><span>깊은 수면</span><strong>${s.deep}분</strong><small>회복성 수면</small></div><div><span>REM</span><strong>${s.rem}분</strong><small>인지 회복</small></div><div><span>효율</span><strong>${s.efficiency}%</strong><small>침대 대비 수면</small></div><div><span>규칙성</span><strong>${s.consistency}%</strong><small>취침·기상 일관성</small></div></section></div>`;}
function healthView(){const v=data.today.vitals;return `<div class="fade-in"><section class="feature-hero"><span class="eyebrow">HEALTH</span><div class="hero-number">${v.vo2max}</div><div class="hero-status">VO₂ Max · 최근 측정</div></section><section class="health-grid">${[['HRV',`${v.hrv} ms`],['안정 시 심박',`${v.rhr} bpm`],['호흡수',`${v.resp} BrPM`],['혈중 산소',`${v.spo2}%`],['체중',`${v.weight} kg`],['BMI',v.bmi],['체지방률',`${v.bodyFat}%`],['제지방량',`${v.leanMass} kg`]].map(x=>`<div class="health-card"><span class="label">${x[0]}</span><strong>${x[1]}</strong><div class="state">최근 측정값</div></div>`).join('')}</section></div>`;}
function workoutView(){return `<div class="fade-in"><section class="feature-hero"><span class="eyebrow">STRENGTH</span><div class="hero-number">근력운동</div><div class="hero-status">최근 기록과 수행 추세</div></section><section class="workout-block"><h3>최근 운동</h3>${(data.strength.recent||[]).map(x=>`<div class="list-row"><div><strong>${x.name}</strong><div class="meta">${x.date}</div></div><span>${x.summary}</span></div>`).join('')||'<div class="empty">최근 기록 없음</div>'}</section><section class="workout-block"><h3>기존 Apps Script 연동</h3><input id="gasInput" class="input-dark" value="${getGasUrl()}" placeholder="Apps Script /exec URL"><button id="saveGas" class="workout-cta secondary">연동 URL 저장</button></section></div>`;}
function trainingView(){const t=data.training;return `<div class="fade-in"><section class="load-hero"><div class="load-stat"><span>ATL</span><strong>${t.atl}</strong><small>급성 부하</small></div><div class="load-stat"><span>CTL</span><strong>${t.ctl}</strong><small>만성 부하</small></div><div class="load-stat"><span>TSB</span><strong>${t.tsb}</strong><small>훈련 밸런스</small></div></section><section class="analysis-card"><div class="analysis-title"><h2>TSB 최근 추세</h2></div>${proChart([-3,-1,0,2,1,3,t.tsb],{color:'#67b8ff',baseline:0})}</section><section class="training-block"><h3>운동 후 심박수 회복</h3><strong style="font-size:42px">${t.hrRecovery} BPM</strong></section></div>`;}

function render(){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.route===route));title.textContent=route==='today'?'오늘':route==='health'?'건강':route==='journal'?'식단':route==='workout'?'운동':route==='training'?'트레이닝':route.startsWith('detail:')?'상세':'오늘';main.innerHTML=route==='today'?todayView():route==='health'?healthView():route==='journal'?renderNutrition(data,nutritionChartKey):route==='workout'?workoutView():route==='training'?trainingView():route.startsWith('detail:')?detailView(route.split(':')[1]):todayView();bindDynamic();}
function bindDynamic(){main.querySelectorAll('[data-detail]').forEach(el=>el.addEventListener('click',()=>{route=`detail:${el.dataset.detail}`;render();}));main.querySelectorAll('[data-route-go]').forEach(el=>el.addEventListener('click',()=>{route=el.dataset.routeGo;render();}));main.querySelector('[data-back]')?.addEventListener('click',()=>{route='today';render();});main.querySelector('#saveGas')?.addEventListener('click',()=>{setGasUrl(main.querySelector('#gasInput').value);alert('연동 URL을 저장했습니다.');});if(route==='journal'){bindNutrition(main,{getData:()=>data,setData:v=>{data=v;},rerender:render,getChartKey:()=>nutritionChartKey,setChartKey:v=>{nutritionChartKey=v;}});}}
document.querySelectorAll('.nav-item').forEach(el=>el.addEventListener('click',()=>{route=el.dataset.route;render();}));
syncBtn.addEventListener('click',async()=>{syncBtn.disabled=true;syncBtn.textContent='…';data=await refreshRemote();render();syncBtn.textContent='↻';syncBtn.disabled=false;});
render();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));